#include "InputUtils.hpp"

const char* toString(KeyCode keycode) {
	switch (keycode) {
		using enum KeyCode;
	case SPACE: return "Space";
	case APOSTROPHE: return "Apostrophe";
	case COMMA: return "Comma";
	case MINUS: return "Minus";
	case PERIOD: return "Period";
	case SLASH: return "Slash";
	case ALPHA_0: return "Alpha0";
	case ALPHA_1: return "Alpha1";
	case ALPHA_2: return "Alpha2";
	case ALPHA_3: return "Alpha3" ;
	case ALPHA_4: return "Alpha4";
	case ALPHA_5: return "Alpha5";
	case ALPHA_6: return "Alpha6";
	case ALPHA_7: return "Alpha7";
	case ALPHA_8: return "Alpha8";
	case ALPHA_9: return "Alpha9";
	case SEMICOLON: return "Semicolon";
	case EQUALS: return "Equals";
	case A: return "A";
	case B: return "B";
	case C: return "C";
	case D: return "D";
	case E: return "E";
	case F: return "F";
	case G:	return "G";
	case H:	return "H";
	case I:	return "I";
	case J:	return "J";
	case K:	return "K";
	case L:	return "L";
	case M:	return "M";
	case N:	return "N";
	case O:	return "O";
	case P:	return "P";
	case Q:	return "Q";
	case R:	return "R";
	case S:	return "S";
	case T:	return "T";
	case U:	return "U";
	case V:	return "V";
	case W:	return "W";
	case X:	return "X";
	case Y:	return "Y";
	case Z:	return "Z";
	case LEFT_BRACKET: return "LeftBracket";
	case BACKSLASH: return "Backslash";
	case RIGHT_BRACKET: return "RightBracket";
	case GRAVE_ACCENT: return "GraveAccent";
	case ESCAPE: return "Escape";
	case ENTER: return "Enter";
	case TAB: return "Tab";
	case BACKSPACE: return "Backspace";
	case INSERT: return "Insert";
	case DELETE: return "Delete";
	case RIGHT: return "Right";
	case LEFT: return "Left";
	case DOWN: return "Down";
	case UP: return "Up";
	case PAGE_UP: return "PageUp";
	case PAGE_DOWN: return "PageDown";
	case HOME: return "Home";
	case END: return "End";
	case CAPS_LOCK: return "CapsLock";
	case SCROLL_LOCK: return "ScrollLock";
	case NUM_LOCK: return "NumLock";
	case PRINT_SCREEN: return "PrintScreen";
	case PAUSE: return "Pause";
	case F1: return "F1";
	case F2: return "F2";
	case F3: return "F3";
	case F4: return "F4";
	case F5: return "F5";
	case F6: return "F6";
	case F7: return "F7";
	case F8: return "F8";
	case F9: return "F9";
	case F10: return "F10";
	case F11: return "F11";
	case F12: return "F12";
	case F13: return "F13";
	case F14: return "F14";
	case F15: return "F15";
	case F16: return "F16";
	case F17: return "F17";
	case F18: return "F18";
	case F19: return "F19";
	case F20: return "F20";
	case F21: return "F21";
	case F22: return "F22";
	case F23: return "F23";
	case F24: return "F24";
	case F25: return "F25";
	case KEYPAD_0: return "Keypad0" ;
	case KEYPAD_1: return "Keypad1";
	case KEYPAD_2: return "Keypad2";
	case KEYPAD_3: return "Keypad3";
	case KEYPAD_4: return "Keypad4";
	case KEYPAD_5: return "Keypad5";
	case KEYPAD_6: return "Keypad6";
	case KEYPAD_7: return "Keypad7";
	case KEYPAD_8: return "Keypad8";
	case KEYPAD_9: return "Keypad9";
	case KEYPAD_DECIMAL: return "KeypadDecimal";
	case KEYPAD_DIVIDE: return "KeypadDivide";
	case KEYPAD_MULTIPLY: return "KeypadMultiply";
	case KEYPAD_SUBTRACT: return "KeypadSubtract";
	case KEYPAD_ADD: return "KeypadAdd";
	case KEYPAD_ENTER: return "KeypadEnter";
	case KEYPAD_EQUALS: return "KeypadEquals";
	case LEFT_SHIFT: return "LeftShift";
	case LEFT_CONTROL: return "LeftControl";
	case LEFT_ALT: return "LeftAlt";
	case LEFT_SUPER: return "LeftSuper";
	case RIGHT_SHIFT: return "RightShift";
	case RIGHT_CONTROL: return "RightControl";
	case RIGHT_ALT: return "RightAlt";
	case RIGHT_SUPER: return "RightSuper";
	case MENU: return "Menu";

	case COUNT:
	default: return "unknown";
	}
}