#include "InputUtils.hpp"

const char* toString(KeyCode keycode) {
	switch (keycode) {
		using enum KeyCode;
	case KeyCode(0): return "left click";
	case KeyCode(1): return "right click";
	case KeyCode(2): return "middle click";
	case SPACE: return "space";
	case APOSTROPHE: return "apostrophe";
	case COMMA: return "comma";
	case MINUS: return "minus";
	case PERIOD: return "period";
	case SLASH: return "slash";
	case ALPHA_0: return "alpha 0";
	case ALPHA_1: return "alpha 1";
	case ALPHA_2: return "alpha 2";
	case ALPHA_3: return "alpha 3" ;
	case ALPHA_4: return "alpha 4";
	case ALPHA_5: return "alpha 5";
	case ALPHA_6: return "alpha 6";
	case ALPHA_7: return "alpha 7";
	case ALPHA_8: return "alpha 8";
	case ALPHA_9: return "alpha 9";
	case SEMICOLON: return "semicolon";
	case EQUALS: return "equals";
	case A: return "A";
	case B: return "B";
	case C: return "C";
	case D: return "D";
	case E: return "E";
	case F: return "F";
	case G:	return "G";
	case H:	return "H";
	case I:	return "I";
	case J:	return "J";
	case K:	return "K";
	case L:	return "L";
	case M:	return "M";
	case N:	return "N";
	case O:	return "O";
	case P:	return "P";
	case Q:	return "Q";
	case R:	return "R";
	case S:	return "S";
	case T:	return "T";
	case U:	return "U";
	case V:	return "V";
	case W:	return "W";
	case X:	return "X";
	case Y:	return "Y";
	case Z:	return "Z";
	/*case A: return "a";
	case B: return "b";
	case C: return "c";
	case D: return "d";
	case E: return "e";
	case F: return "f";
	case G:	return "g";
	case H:	return "h";
	case I:	return "i";
	case J:	return "j";
	case K:	return "k";
	case L:	return "l";
	case M:	return "m";
	case N:	return "n";
	case O:	return "o";
	case P:	return "p";
	case Q:	return "q";
	case R:	return "r";
	case S:	return "s";
	case T:	return "t";
	case U:	return "u";
	case V:	return "v";
	case W:	return "w";
	case X:	return "x";
	case Y:	return "y";
	case Z:	return "z";*/
	case LEFT_BRACKET: return "left bracket";
	case BACKSLASH: return "backslash";
	case RIGHT_BRACKET: return "right bracket";
	case GRAVE_ACCENT: return "grave accent";
	case ESCAPE: return "escape";
	case ENTER: return "enter";
	case TAB: return "tab";
	case BACKSPACE: return "backspace";
	case INSERT: return "insert";
	case DELETE: return "delete";
	case RIGHT: return "right";
	case LEFT: return "left";
	case DOWN: return "down";
	case UP: return "up";
	case PAGE_UP: return "page up";
	case PAGE_DOWN: return "page down";
	case HOME: return "home";
	case END: return "end";
	case CAPS_LOCK: return "caps lock";
	case SCROLL_LOCK: return "scroll lock";
	case NUM_LOCK: return "num lock";
	case PRINT_SCREEN: return "print screen";
	case PAUSE: return "pause";
	case F1: return "F1";
	case F2: return "F2";
	case F3: return "F3";
	case F4: return "F4";
	case F5: return "F5";
	case F6: return "F6";
	case F7: return "F7";
	case F8: return "F8";
	case F9: return "F9";
	case F10: return "F10";
	case F11: return "F11";
	case F12: return "F12";
	case F13: return "F13";
	case F14: return "F14";
	case F15: return "F15";
	case F16: return "F16";
	case F17: return "F17";
	case F18: return "F18";
	case F19: return "F19";
	case F20: return "F20";
	case F21: return "F21";
	case F22: return "F22";
	case F23: return "F23";
	case F24: return "F24";
	case F25: return "F25";
	case KEYPAD_0: return "keypad 0" ;
	case KEYPAD_1: return "keypad 1";
	case KEYPAD_2: return "keypad 2";
	case KEYPAD_3: return "keypad 3";
	case KEYPAD_4: return "keypad 4";
	case KEYPAD_5: return "keypad 5";
	case KEYPAD_6: return "keypad 6";
	case KEYPAD_7: return "keypad 7";
	case KEYPAD_8: return "keypad 8";
	case KEYPAD_9: return "keypad 9";
	case KEYPAD_DECIMAL: return "keypad decimal";
	case KEYPAD_DIVIDE: return "keypad divide";
	case KEYPAD_MULTIPLY: return "keypad multiply";
	case KEYPAD_SUBTRACT: return "keypad subtract";
	case KEYPAD_ADD: return "keypad add";
	case KEYPAD_ENTER: return "keypad enter";
	case KEYPAD_EQUALS: return "keypad equals";
	case LEFT_SHIFT: return "left shift";
	case LEFT_CONTROL: return "left control";
	case LEFT_ALT: return "left alt";
	case LEFT_SUPER: return "left super";
	case RIGHT_SHIFT: return "right shift";
	case RIGHT_CONTROL: return "right control";
	case RIGHT_ALT: return "right alt";
	case RIGHT_SUPER: return "right super";
	case MENU: return "menu";

	case COUNT:
	default: return "unknown";
	}
}